package handlers

// Compose generation from running containers ("export to repository").

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// generateCompose builds a docker-compose.yml from inspect data
func generateCompose(containers []map[string]any) string {
	// First pass: collect all custom network names and named volume names
	// so we can emit valid top-level blocks.
	allNetworks := map[string]bool{}
	allVolumes := map[string]bool{}
	for _, c := range containers {
		hostConfig := getMap(c, "HostConfig")
		networkMode := getString(hostConfig, "NetworkMode")
		if networkMode != "host" && !strings.HasPrefix(networkMode, "container:") {
			for netName := range getMap(getMap(c, "NetworkSettings"), "Networks") {
				if netName != "bridge" && netName != "host" && netName != "none" {
					allNetworks[netName] = true
				}
			}
		}
		if mounts, ok := c["Mounts"].([]any); ok {
			for _, m := range mounts {
				if mount, ok := m.(map[string]any); ok {
					if getString(mount, "Type") == "volume" {
						if vol := getString(mount, "Name"); vol != "" {
							allVolumes[vol] = true
						}
					}
				}
			}
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by DPlaneOS Git Sync\n")
	b.WriteString("# " + time.Now().Format(time.RFC3339) + "\n\n")
	b.WriteString("services:\n")

	for _, c := range containers {
		name := getString(c, "Name")
		name = strings.TrimPrefix(name, "/")
		if name == "" {
			continue
		}

		config := getMap(c, "Config")
		hostConfig := getMap(c, "HostConfig")
		networkSettings := getMap(c, "NetworkSettings")

		image := getString(config, "Image")
		b.WriteString(fmt.Sprintf("  %s:\n", name))
		b.WriteString(fmt.Sprintf("    image: %s\n", image))

		// Restart policy - read from actual config, not hardcoded
		restartPolicy := "no"
		if rp := getMap(hostConfig, "RestartPolicy"); len(rp) > 0 {
			switch getString(rp, "Name") {
			case "always", "unless-stopped", "on-failure":
				restartPolicy = getString(rp, "Name")
			}
		}
		b.WriteString(fmt.Sprintf("    restart: %s\n", restartPolicy))

		// Environment variables
		if envList, ok := config["Env"].([]any); ok && len(envList) > 0 {
			filtered := filterEnv(envList)
			if len(filtered) > 0 {
				b.WriteString("    environment:\n")
				for _, e := range filtered {
					b.WriteString(fmt.Sprintf("      - %s\n", e))
				}
			}
		}

		// Ports
		if ports := getMap(hostConfig, "PortBindings"); len(ports) > 0 {
			b.WriteString("    ports:\n")
			for containerPort, bindings := range ports {
				if bindList, ok := bindings.([]any); ok {
					for _, bind := range bindList {
						if bm, ok := bind.(map[string]any); ok {
							hostPort := getString(bm, "HostPort")
							cp := strings.Split(containerPort, "/")[0]
							proto := ""
							if strings.HasSuffix(containerPort, "/udp") {
								proto = "/udp"
							}
							b.WriteString(fmt.Sprintf("      - \"%s:%s%s\"\n", hostPort, cp, proto))
						}
					}
				}
			}
		}

		// Mounts: distinguish named volumes from bind mounts
		if mounts, ok := c["Mounts"].([]any); ok && len(mounts) > 0 {
			b.WriteString("    volumes:\n")
			for _, m := range mounts {
				if mount, ok := m.(map[string]any); ok {
					dst := getString(mount, "Destination")
					if dst == "" {
						continue
					}
					mode := ""
					if rw, ok := mount["RW"].(bool); ok && !rw {
						mode = ":ro"
					}
					if getString(mount, "Type") == "volume" {
						volName := getString(mount, "Name")
						if volName != "" {
							b.WriteString(fmt.Sprintf("      - %s:%s%s\n", volName, dst, mode))
						} else {
							b.WriteString(fmt.Sprintf("      - %s%s\n", dst, mode))
						}
					} else {
						src := getString(mount, "Source")
						if src != "" {
							b.WriteString(fmt.Sprintf("      - %s:%s%s\n", src, dst, mode))
						}
					}
				}
			}
		}

		// Network mode (host / container:X) or per-network references
		networkMode := getString(hostConfig, "NetworkMode")
		if networkMode == "host" || strings.HasPrefix(networkMode, "container:") {
			b.WriteString(fmt.Sprintf("    network_mode: \"%s\"\n", networkMode))
		} else {
			if nets := getMap(networkSettings, "Networks"); len(nets) > 0 {
				var netNames []string
				for netName := range nets {
					if netName != "bridge" && netName != "host" && netName != "none" {
						netNames = append(netNames, netName)
					}
				}
				if len(netNames) > 0 {
					sort.Strings(netNames)
					b.WriteString("    networks:\n")
					for _, n := range netNames {
						b.WriteString(fmt.Sprintf("      - %s\n", n))
					}
				}
			}
		}

		// Labels (filter out internal docker labels)
		if labels, ok := config["Labels"].(map[string]any); ok {
			userLabels := map[string]string{}
			for k, v := range labels {
				if !strings.HasPrefix(k, "com.docker.") && !strings.HasPrefix(k, "org.opencontainers.") {
					userLabels[k] = fmt.Sprintf("%v", v)
				}
			}
			if len(userLabels) > 0 {
				b.WriteString("    labels:\n")
				for k, v := range userLabels {
					b.WriteString(fmt.Sprintf("      %s: \"%s\"\n", k, v))
				}
			}
		}

		b.WriteString("\n")
	}

	// Top-level networks block - compose rejects service-level network refs without this
	if len(allNetworks) > 0 {
		netNames := make([]string, 0, len(allNetworks))
		for n := range allNetworks {
			netNames = append(netNames, n)
		}
		sort.Strings(netNames)
		b.WriteString("networks:\n")
		for _, n := range netNames {
			b.WriteString(fmt.Sprintf("  %s:\n", n))
			b.WriteString("    external: true\n")
		}
		b.WriteString("\n")
	}

	// Top-level volumes block for named volumes
	if len(allVolumes) > 0 {
		volNames := make([]string, 0, len(allVolumes))
		for v := range allVolumes {
			volNames = append(volNames, v)
		}
		sort.Strings(volNames)
		b.WriteString("volumes:\n")
		for _, v := range volNames {
			b.WriteString(fmt.Sprintf("  %s:\n", v))
			b.WriteString("    external: true\n")
		}
		b.WriteString("\n")
	}

	return b.String()
}

// Helper functions for safe type assertions
func getString(m map[string]any, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getMap(m map[string]any, key string) map[string]any {
	if v, ok := m[key].(map[string]any); ok {
		return v
	}
	return map[string]any{}
}

func filterEnv(envList []any) []string {
	// Filter out common default env vars that aren't user-configured
	skip := map[string]bool{"PATH": true, "HOME": true, "HOSTNAME": true, "TERM": true}
	var result []string
	for _, e := range envList {
		s, ok := e.(string)
		if !ok {
			continue
		}
		key := strings.SplitN(s, "=", 2)[0]
		if !skip[key] {
			result = append(result, s)
		}
	}
	return result
}
