# hardware-configuration.nix
# ─────────────────────────────────────────────────────────────────────────────
# This file is generated by `nixos-generate-config --root /mnt` during install.
# It contains machine-specific hardware detection (filesystems, kernel modules,
# CPU type, etc.) that nixos-generate-config discovers automatically.
#
# DO NOT use this stub file on a real install - it will be overwritten.
# It is included here only so `nix flake check` and `nixos-rebuild dry-run`
# work on the source tree without a real machine present.
#
# To regenerate for your hardware:
#   nixos-generate-config --root /mnt
# ─────────────────────────────────────────────────────────────────────────────

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Populated by nixos-generate-config on your actual hardware.
  # The values below are placeholders and WILL be replaced.

  boot.initrd.availableKernelModules = [ "ahci" "nvme" "xhci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules          = [];
  boot.kernelModules                 = [ "kvm-intel" ];
  boot.extraModulePackages           = [];

  # Filesystems - replaced by nixos-generate-config.
  # disko.nix manages the actual partition layout; these entries are
  # generated from it automatically during install.
  fileSystems."/" = {
    device = "/dev/disk/by-label/system-a";
    fsType = "ext4";
    options = [ "noatime" "errors=remount-ro" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/ESP";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-label/persist";
    fsType = "ext4";
    options = [ "noatime" "errors=remount-ro" ];
    neededForBoot = true;
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
