# D-PlaneOS — Impermanence Layer (Task 4.4)
# ─────────────────────────────────────────────────────────────────────────────
# Makes the system root ephemeral: everything NOT in /persist is wiped on reboot.
#
# Mental model:
#   /           — ephemeral ext4 (slot A or B). Wiped clean every OTA update.
#                 Contains only the NixOS system closure (immutable store paths).
#   /persist    — durable ext4. Never wiped. All state lives here.
#   /nix/store  — populated by NixOS activation. Ephemeral by design.
#
# What survives reboots (bound from /persist/* → live path):
#   - D-PlaneOS databases (main + audit)
#   - Audit HMAC key
#   - GitOps state.yaml and repo checkout
#   - Machine SSH host keys (so clients don't see key-changed warnings)
#   - NixOS machine-id (for stable journald cursor)
#   - Rotated logs
#   - Samba state (passdb, tdb files)
#   - NetworkManager/networkd lease files (optional, stable IP helps)
#
# What does NOT survive (intentionally ephemeral):
#   - /tmp, /run, /var/run — always tmpfs anyway
#   - Package caches, build artifacts
#   - Anything not explicitly listed below
#
# Boundary rule:
#   NixOS owns /persist/nixos/ and /persist/ssh/
#   D-PlaneOS daemon owns /persist/dplaneos/
#   No other service writes to /persist without an entry here.
# ─────────────────────────────────────────────────────────────────────────────

{ config, lib, pkgs, ... }:

{
  # ── impermanence module input (comes from flake.nix inputs) ────────────────
  # The module is imported here; it is declared as a flake input in flake.nix.
  imports = [];  # module itself added via flake, not here

  # ── Ensure /persist is mounted before activation ────────────────────────────
  # fileSystems entry is generated by disko.nix. We declare neededForBoot
  # here to guarantee it is available during early initrd.
  fileSystems."/persist".neededForBoot = true;

  # ── impermanence: bind-mount /persist/* into their live locations ─────────
  environment.persistence."/persist" = {

    hideMounts = true;   # hide bind-mounts from df/findmnt output for cleanliness

    # ── Top-level directories to bind from /persist ──────────────────────
    directories = [

      # ── D-PlaneOS daemon state (the boundary: daemon owns this subtree) ─
      # All DB files, keys, gitops repo live under /persist/dplaneos/
      # The daemon's -db flag is set to /var/lib/dplaneos/dplaneos.db
      # which is bind-mounted from /persist/dplaneos/
      {
        directory = "/var/lib/dplaneos";
        user      = "root";
        group     = "root";
        mode      = "0755";
      }

      # ── Daemon logs ─────────────────────────────────────────────────────
      {
        directory = "/var/log/dplaneos";
        user      = "root";
        group     = "root";
        mode      = "0755";
      }

      # ── Daemon config (smb.conf, exports, dplaneos.conf) ────────────────
      # NixOS owns /etc but the daemon owns /etc/dplaneos/*.
      # We persist the daemon's subtree only.
      {
        directory = "/etc/dplaneos";
        user      = "root";
        group     = "root";
        mode      = "0755";
      }

      # ── Samba state (passdb.tdb, secrets.tdb, etc.) ─────────────────────
      # Without this, Samba user passwords are lost on reboot.
      {
        directory = "/var/lib/samba";
        user      = "root";
        group     = "root";
        mode      = "0755";
      }

      # ── Samba logs ───────────────────────────────────────────────────────
      {
        directory = "/var/log/samba";
        user      = "root";
        group     = "root";
        mode      = "0755";
      }

      # ── NFS exports state ────────────────────────────────────────────────
      {
        directory = "/var/lib/nfs";
        user      = "root";
        group     = "root";
        mode      = "0755";
      }

      # ── Docker (container state, images, volumes) ────────────────────────
      # Docker's overlay2 graph is large and contains container state.
      # Without this, all containers are gone after reboot.
      {
        directory = "/var/lib/docker";
        user      = "root";
        group     = "root";
        mode      = "0710";
      }

      # ── NetworkManager leases (optional) ────────────────────────────────
      # Helps maintain stable DHCP addresses on networks that honour client-id.
      {
        directory = "/var/lib/NetworkManager";
        user      = "root";
        group     = "root";
        mode      = "0755";
      }

      # ── systemd-networkd lease files ────────────────────────────────────
      {
        directory = "/var/lib/systemd/network";
        user      = "systemd-network";
        group     = "systemd-network";
        mode      = "0755";
      }

      # ── Avahi host database ──────────────────────────────────────────────
      {
        directory = "/var/lib/avahi-daemon";
        user      = "avahi";
        group     = "avahi";
        mode      = "0755";
      }

    ]; # directories

    # ── Individual files to bind from /persist ────────────────────────────
    files = [

      # ── Machine ID ───────────────────────────────────────────────────────
      # A stable machine-id ensures journald cursors survive reboots.
      # Without this, log rotation and journald forwarding break across reboots.
      "/etc/machine-id"

      # ── NixOS host SSH keys ───────────────────────────────────────────────
      # Persisting host keys means SSH clients don't see "host key changed"
      # warnings after an OTA update to a new system slot.
      "/etc/ssh/ssh_host_rsa_key"
      "/etc/ssh/ssh_host_rsa_key.pub"
      "/etc/ssh/ssh_host_ed25519_key"
      "/etc/ssh/ssh_host_ed25519_key.pub"

      # ── ZFS hostid ───────────────────────────────────────────────────────
      # NixOS writes this from networking.hostId. Persisting avoids
      # a ZFS "pool was last used by another system" error after slot swap.
      "/etc/hostid"

    ]; # files

  }; # environment.persistence."/persist"

  # ── Create /persist subdirectories on first boot ───────────────────────────
  # systemd-tmpfiles creates these if they don't exist. Idempotent.
  systemd.tmpfiles.rules = [
    "d /persist/dplaneos          0755 root root -"
    "d /persist/dplaneos/gitops   0755 root root -"
    "d /persist/log               0755 root root -"
    "d /persist/ssh               0755 root root -"
    "d /persist/nixos             0755 root root -"
  ];

  # ── Warn loudly if /persist is missing at boot ───────────────────────────
  # This catches a misconfigured or unmounted persist partition before
  # the daemon starts writing to the ephemeral root.
  systemd.services.persist-health-check = {
    description = "D-PlaneOS: verify /persist is mounted";
    wantedBy    = [ "local-fs.target" ];
    after       = [ "local-fs.target" ];
    before      = [ "dplaned.service" ];
    serviceConfig = {
      Type            = "oneshot";
      RemainAfterExit = true;
      ExecStart       = pkgs.writeShellScript "persist-check" ''
        #!/bin/sh
        set -e
        if ! mountpoint -q /persist; then
          echo "CRITICAL: /persist is NOT mounted. Daemon state will be lost on reboot."
          echo "Check disko.nix and fstab. Halting D-PlaneOS startup."
          exit 1
        fi
        # Verify key directories exist on the persist partition
        for d in dplaneos log; do
          if [ ! -d "/persist/$d" ]; then
            mkdir -p "/persist/$d"
            echo "Created /persist/$d"
          fi
        done
        echo "persist-health-check: OK (/persist is mounted and writable)"
      '';
    };
  };
}
