package gitops

import (
	"database/sql"
	"errors"
	"fmt"
	"log"
	"strings"
	"sync"
	"time"

	"dplaned/internal/cmdutil"
)

// ═══════════════════════════════════════════════════════════════════════════════
//  CLONE SYNC AND APPLIED-COMMIT TRACKING
//
//  The state clone holds two kinds of commits: commits authored elsewhere
//  (operators, CI) that describe desired state, and snapshot commits this node
//  writes after GUI changes (CommitAll), which are derived from live state and
//  can always be regenerated.
//
//  The synced commit is the commit the live system corresponds to: the commit
//  this node last pushed, or the commit it last applied. Remote commits beyond
//  it are not applied yet; CommitAll refuses to snapshot live state over them,
//  because the snapshot would silently revert them.
// ═══════════════════════════════════════════════════════════════════════════════

// ErrUnappliedRemote is returned by CommitAll when the remote has commits that
// are not applied to this system yet.
var ErrUnappliedRemote = errors.New("the Git repository has changes that are not applied to this system yet")

const syncedSHAKey = "gitops_synced_sha"

// syncedStore persists the synced commit (the settings table in production).
type syncedStore interface {
	get() string
	set(sha string) error
}

type dbSynced struct{ db *sql.DB }

func (s dbSynced) get() string          { return getSyncedSHA(s.db) }
func (s dbSynced) set(sha string) error { return setSyncedSHA(s.db, sha) }

func getSyncedSHA(db *sql.DB) string {
	var sha string
	_ = db.QueryRow(`SELECT value FROM settings WHERE key = $1`, syncedSHAKey).Scan(&sha)
	return sha
}

func setSyncedSHA(db *sql.DB, sha string) error {
	_, err := db.Exec(`INSERT INTO settings (key, value) VALUES ($1, $2)
		ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`, syncedSHAKey, sha)
	return err
}

// SyncedCommit returns the commit the live system corresponds to ("" if none).
func SyncedCommit(db *sql.DB) string { return getSyncedSHA(db) }

// FullyApplied reports whether an apply applied every item: pool operations
// deferred by the HA guard leave the live system behind the clone.
func FullyApplied(r *ApplyResult) bool {
	if r == nil || r.Failed != "" {
		return false
	}
	for _, a := range r.Applied {
		if strings.HasPrefix(a, "[DEFERRED") {
			return false
		}
	}
	return true
}

// RecordApplied marks the clone's current HEAD as applied to the live system.
// Call it after an apply that applied every item (nothing deferred).
func RecordApplied(db *sql.DB, repoDir string) error {
	head, err := gitOut(repoDir, nil, "rev-parse", "HEAD")
	if err != nil {
		return fmt.Errorf("record applied commit: %w", err)
	}
	return setSyncedSHA(db, head)
}

// gitOut runs git in dir and returns trimmed stdout. env carries credentials
// for commands that talk to the remote.
func gitOut(dir string, env []string, args ...string) (string, error) {
	var out []byte
	var err error
	if env != nil {
		out, err = cmdutil.RunInDirWithEnv(cmdutil.TimeoutMedium, dir, env, "git", args...)
	} else {
		out, err = cmdutil.RunFastInDir(dir, "git", args...)
	}
	if err != nil {
		return "", fmt.Errorf("git %s: %v: %s", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return strings.TrimSpace(string(out)), nil
}

func isAncestor(dir, ancestor, descendant string) bool {
	_, err := cmdutil.RunFastInDir(dir, "git", "merge-base", "--is-ancestor", ancestor, descendant)
	return err == nil
}

// fetchRemote fetches branch from origin and returns the remote commit, or ""
// when the remote branch does not exist yet (fresh repository). Network and
// authentication errors are returned, never treated as "fresh".
func fetchRemote(dir string, env []string, branch string) (string, error) {
	heads, err := gitOut(dir, envOrEmpty(env), "ls-remote", "--heads", "origin", branch)
	if err != nil {
		return "", err
	}
	if heads == "" {
		return "", nil
	}
	if _, err := gitOut(dir, envOrEmpty(env), "fetch", "origin", branch); err != nil {
		return "", err
	}
	return gitOut(dir, nil, "rev-parse", "origin/"+branch)
}

func envOrEmpty(env []string) []string {
	if env == nil {
		return []string{}
	}
	return env
}

// syncClone brings the working tree to the remote branch without losing
// anything that matters: it fast-forwards when behind, keeps unpushed local
// commits when ahead, and when the histories diverged it resets to the remote
// (local commits are live-state snapshots, regenerated by the next CommitAll).
// It returns the remote commit ("" for a fresh remote).
func syncClone(dir string, env []string, branch string) (string, error) {
	remote, err := fetchRemote(dir, env, branch)
	if err != nil || remote == "" {
		return remote, err
	}
	local, err := gitOut(dir, nil, "rev-parse", "HEAD")
	if err != nil {
		return remote, err
	}
	switch {
	case local == remote, isAncestor(dir, remote, local):
		// Up to date, or ahead with unpushed snapshot commits.
	case isAncestor(dir, local, remote):
		if _, err := gitOut(dir, nil, "merge", "--ff-only", "origin/"+branch); err != nil {
			return remote, err
		}
	default:
		log.Printf("GITOPS: local clone diverged from origin/%s; resetting to the remote (snapshot commits are regenerated from live state)", branch)
		if _, err := gitOut(dir, nil, "reset", "--hard", "origin/"+branch); err != nil {
			return remote, err
		}
	}
	return remote, nil
}

// ── Last commit result (shown on the GitOps page) ─────────────────────────────

// CommitStatus is the outcome of the last GUI write-back.
type CommitStatus struct {
	At      time.Time `json:"at"`
	OK      bool      `json:"ok"`
	Skipped bool      `json:"skipped"` // not the writer, or GitOps disabled
	Error   string    `json:"error,omitempty"`
}

var (
	commitStatusMu sync.RWMutex
	commitStatus   *CommitStatus
	eventHub       DriftBroadcaster
)

// SetEventHub lets background commits report failures over the WebSocket hub.
func SetEventHub(hub DriftBroadcaster) {
	commitStatusMu.Lock()
	eventHub = hub
	commitStatusMu.Unlock()
}

// LastCommitStatus returns the outcome of the last write-back, or nil.
func LastCommitStatus() *CommitStatus {
	commitStatusMu.RLock()
	defer commitStatusMu.RUnlock()
	if commitStatus == nil {
		return nil
	}
	cp := *commitStatus
	return &cp
}

func recordCommitResult(err error) {
	st := &CommitStatus{At: time.Now(), OK: err == nil}
	if err != nil {
		if errors.Is(err, ErrNotWriter) {
			st.OK, st.Skipped = true, true
		}
		st.Error = err.Error()
	}
	commitStatusMu.Lock()
	commitStatus = st
	hub := eventHub
	commitStatusMu.Unlock()
	if err != nil && !st.Skipped && hub != nil {
		hub.Broadcast("gitops.commit_failed", st, "warning")
	}
}
