<?php
/**
 * D-PlaneOS v1.14.0 - Network Management
 * Real network commands for interface/IP/DNS/firewall management
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');

require_once __DIR__ . '/notifications.php';

class NetworkManager {
    private $notifications;
    
    public function __construct() {
        $this->notifications = new NotificationSystem();
    }
    
    private function exec($command, &$output = null, &$returnCode = null) {
        exec($command . ' 2>&1', $output, $returnCode);
        error_log("[Network] $command => $returnCode");
        return $returnCode === 0;
    }
    
    public function listInterfaces() {
        if (!$this->exec("ip -j addr show", $output, $code)) {
            return ['interfaces' => []];
        }
        
        $data = json_decode(implode('', $output), true);
        $interfaces = [];
        
        foreach ($data as $iface) {
            $addresses = [];
            foreach ($iface['addr_info'] ?? [] as $addr) {
                if ($addr['family'] === 'inet' || $addr['family'] === 'inet6') {
                    $addresses[] = $addr['local'] . '/' . $addr['prefixlen'];
                }
            }
            
            $interfaces[] = [
                'name' => $iface['ifname'],
                'state' => $iface['operstate'],
                'mtu' => $iface['mtu'],
                'addresses' => $addresses,
                'mac' => $iface['address'] ?? ''
            ];
        }
        
        return ['interfaces' => $interfaces];
    }
    
    public function setIPAddress($interface, $ip, $netmask) {
        $interface = escapeshellarg($interface);
        $cidr = $ip . '/' . $this->netmaskToCIDR($netmask);
        
        // Flush existing IPs
        $this->exec("ip addr flush dev $interface");
        
        // Set new IP
        if (!$this->exec("ip addr add $cidr dev $interface", $output, $code)) {
            return ['success' => false, 'error' => implode("\n", $output)];
        }
        
        // Bring interface up
        $this->exec("ip link set $interface up");
        
        $this->notifications->create([
            'type' => 'success',
            'title' => 'IP Address Set',
            'message' => "IP $cidr set on $interface",
            'category' => 'network'
        ]);
        
        return ['success' => true];
    }
    
    private function netmaskToCIDR($netmask) {
        $parts = explode('.', $netmask);
        $binary = '';
        foreach ($parts as $part) {
            $binary .= str_pad(decbin($part), 8, '0', STR_PAD_LEFT);
        }
        return substr_count($binary, '1');
    }
    
    public function setDHCP($interface) {
        $interface = escapeshellarg($interface);
        
        if (!$this->exec("dhclient $interface", $output, $code)) {
            return ['success' => false, 'error' => implode("\n", $output)];
        }
        
        $this->notifications->create([
            'type' => 'info',
            'title' => 'DHCP Enabled',
            'message' => "DHCP enabled on $interface",
            'category' => 'network'
        ]);
        
        return ['success' => true];
    }
    
    public function getDNS() {
        if (!file_exists('/etc/resolv.conf')) {
            return ['servers' => []];
        }
        
        $content = file_get_contents('/etc/resolv.conf');
        $servers = [];
        
        foreach (explode("\n", $content) as $line) {
            if (preg_match('/^nameserver\s+(\S+)/', trim($line), $matches)) {
                $servers[] = $matches[1];
            }
        }
        
        return ['servers' => $servers];
    }
    
    public function setDNS($servers) {
        $content = "# Generated by D-PlaneOS\n";
        foreach ($servers as $server) {
            $content .= "nameserver $server\n";
        }
        
        if (file_put_contents('/etc/resolv.conf', $content) === false) {
            return ['success' => false, 'error' => 'Failed to write DNS config'];
        }
        
        $this->notifications->create([
            'type' => 'success',
            'title' => 'DNS Updated',
            'message' => 'DNS servers configured',
            'category' => 'network'
        ]);
        
        return ['success' => true];
    }
    
    public function getRoutes() {
        if (!$this->exec("ip -j route show", $output, $code)) {
            return ['routes' => []];
        }
        
        $routes = json_decode(implode('', $output), true);
        return ['routes' => $routes ?? []];
    }
    
    public function addRoute($destination, $gateway, $interface = null) {
        $cmd = "ip route add $destination via $gateway";
        if ($interface) {
            $cmd .= " dev " . escapeshellarg($interface);
        }
        
        if (!$this->exec($cmd, $output, $code)) {
            return ['success' => false, 'error' => implode("\n", $output)];
        }
        
        return ['success' => true];
    }
    
    public function deleteRoute($destination) {
        if (!$this->exec("ip route del $destination", $output, $code)) {
            return ['success' => false, 'error' => implode("\n", $output)];
        }
        
        return ['success' => true];
    }
    
    public function getFirewallRules() {
        if (!$this->exec("iptables -L -n -v", $output, $code)) {
            return ['rules' => 'Firewall not available'];
        }
        
        return ['rules' => implode("\n", $output)];
    }
    
    public function addFirewallRule($chain, $rule) {
        $chain = escapeshellarg($chain);
        
        if (!$this->exec("iptables -A $chain $rule", $output, $code)) {
            return ['success' => false, 'error' => implode("\n", $output)];
        }
        
        $this->notifications->create([
            'type' => 'success',
            'title' => 'Firewall Rule Added',
            'message' => "Rule added to $chain",
            'category' => 'network'
        ]);
        
        return ['success' => true];
    }
    
    public function getHostname() {
        if (!$this->exec("hostname", $output, $code)) {
            return ['hostname' => 'unknown'];
        }
        
        return ['hostname' => trim($output[0] ?? 'unknown')];
    }
    
    public function setHostname($hostname) {
        if (!$this->exec("hostnamectl set-hostname " . escapeshellarg($hostname), $output, $code)) {
            return ['success' => false, 'error' => implode("\n", $output)];
        }
        
        $this->notifications->create([
            'type' => 'success',
            'title' => 'Hostname Changed',
            'message' => "Hostname set to $hostname",
            'category' => 'network'
        ]);
        
        return ['success' => true];
    }
    // ─── Tailscale Management ──────────────────────────────
    // One-click WireGuard tunnel — makes the NAS reachable from anywhere
    // without port forwarding.
    
    public function tailscaleStatus() {
        $result = [
            'installed' => false,
            'running'   => false,
            'ip'        => null,
            'peers'     => 0,
            'status'    => 'not_installed'
        ];
        
        // Is the binary present?
        $this->exec("which tailscale", $out, $code);
        if ($code !== 0) {
            return $result;
        }
        $result['installed'] = true;
        $result['status']    = 'installed_not_running';
        
        // Is the service active?
        $this->exec("systemctl is-active tailscaled", $out, $code);
        if ($code !== 0) {
            return $result;
        }
        $result['running'] = true;
        
        // Get detailed status via JSON output
        $this->exec("tailscale status --json", $out, $code);
        if ($code === 0) {
            $json = json_decode(implode('', $out), true);
            if ($json && isset($json['Self'])) {
                $result['ip']     = $json['Self']['TailAddr'] ?? null;
                $result['peers']  = count($json['Peers'] ?? []);
                $result['status'] = 'connected';
            } else {
                $result['status'] = 'waiting_auth';
            }
        }
        
        return $result;
    }
    
    public function tailscaleInstall() {
        $script = '/var/www/dplaneos/scripts/install-tailscale.sh';
        
        if (!file_exists($script)) {
            return ['success' => false, 'error' => 'Install helper not found: ' . $script];
        }
        
        if (!$this->exec("sudo " . escapeshellarg($script), $out, $code)) {
            return ['success' => false, 'error' => implode("\n", $out)];
        }
        
        $this->exec("sudo systemctl enable tailscaled");
        $this->exec("sudo systemctl start tailscaled");
        
        $this->notifications->create([
            'type'     => 'success',
            'title'    => 'Tailscale Installed',
            'message'  => 'Tailscale installed. Click Connect to link your account.',
            'category' => 'network'
        ]);
        
        return ['success' => true, 'message' => 'Tailscale installed and daemon started.'];
    }
    
    public function tailscaleUp() {
        $this->exec("sudo tailscale up --accept-routes", $out, $code);
        
        $authUrl = null;
        foreach ($out as $line) {
            if (preg_match('/(https:\/\/login\.tailscale\.com\/\S+)/', $line, $m)) {
                $authUrl = $m[1];
                break;
            }
        }
        
        $this->notifications->create([
            'type'     => 'info',
            'title'    => 'Tailscale Connecting',
            'message'  => $authUrl ? 'Open the auth URL in your browser' : 'Connection initiated',
            'category' => 'network'
        ]);
        
        return [
            'success'  => true,
            'auth_url' => $authUrl,
            'output'   => implode("\n", $out)
        ];
    }
    
    public function tailscaleDown() {
        if (!$this->exec("sudo tailscale down", $out, $code)) {
            return ['success' => false, 'error' => implode("\n", $out)];
        }
        
        $this->notifications->create([
            'type'     => 'info',
            'title'    => 'Tailscale Disconnected',
            'message'  => 'Tailscale tunnel closed',
            'category' => 'network'
        ]);
        
        return ['success' => true];
    }
}

$network = new NetworkManager();
$action = $_GET['action'] ?? $_POST['action'] ?? 'list';

switch ($action) {
    case 'list':
        echo json_encode($network->listInterfaces());
        break;
    
    case 'set_ip':
        $data = json_decode(file_get_contents('php://input'), true);
        echo json_encode($network->setIPAddress($data['interface'], $data['ip'], $data['netmask']));
        break;
    
    case 'set_dhcp':
        $data = json_decode(file_get_contents('php://input'), true);
        echo json_encode($network->setDHCP($data['interface']));
        break;
    
    case 'get_dns':
        echo json_encode($network->getDNS());
        break;
    
    case 'set_dns':
        $data = json_decode(file_get_contents('php://input'), true);
        echo json_encode($network->setDNS($data['servers']));
        break;
    
    case 'routes':
        echo json_encode($network->getRoutes());
        break;
    
    case 'add_route':
        $data = json_decode(file_get_contents('php://input'), true);
        echo json_encode($network->addRoute($data['destination'], $data['gateway'], $data['interface'] ?? null));
        break;
    
    case 'delete_route':
        $data = json_decode(file_get_contents('php://input'), true);
        echo json_encode($network->deleteRoute($data['destination']));
        break;
    
    case 'firewall':
        echo json_encode($network->getFirewallRules());
        break;
    
    case 'add_firewall_rule':
        $data = json_decode(file_get_contents('php://input'), true);
        echo json_encode($network->addFirewallRule($data['chain'], $data['rule']));
        break;
    
    case 'get_hostname':
        echo json_encode($network->getHostname());
        break;
    
    case 'set_hostname':
        $data = json_decode(file_get_contents('php://input'), true);
        echo json_encode($network->setHostname($data['hostname']));
        break;
    
    case 'tailscale_status':
        echo json_encode($network->tailscaleStatus());
        break;
    
    case 'tailscale_install':
        echo json_encode($network->tailscaleInstall());
        break;
    
    case 'tailscale_up':
        echo json_encode($network->tailscaleUp());
        break;
    
    case 'tailscale_down':
        echo json_encode($network->tailscaleDown());
        break;
    
    default:
        echo json_encode(['error' => 'Unknown action']);
}
